// SPDX-License-Identifier: EPL-2.0

#ifndef AHI_LOOP_H
#define AHI_LOOP_H

#define AHI_LOOP_STATE_INITIAL     0
#define AHI_LOOP_STATE_RUNNING     1
#define AHI_LOOP_STATE_STOPPING    2
#define AHI_LOOP_STATE_STOPPED     3
#define AHI_LOOP_STATE_TERMINATING 4
#define AHI_LOOP_STATE_TERMINATED  5

#endif
